version: 2


models:
  - name: fct_customer_orders
    description: sugma
    columns:
      - name: nvsr
        tests:
          - not_null
          - accepted_values:
              values: ['new', 'return']
      - name: is_new
        tests:
          - is_true:
              severity: warn
              new_arg: false
