practice_dbt:
  outputs:
    dev:
      dataset: dbt_dataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: C:\codingtime\my_dbt_project\dbt_user_creds.json
      location: US
      method: service-account
      priority: interactive
      project: big-query-project-374718
      threads: 1
      type: bigquery
  target: dev # This is the default profile that dbt will run
